spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

email:
  host: smtp.gmail.com
  port: 587
  username: noreply.logsight@gmail.com
  password: logsight2021123!

app:
  baseUrl: https://logsight.ai/
  qualityUrl: http://data-input-rest-api:5444/

#change this for prod
stripe:
  sk: "sk_test_51ILUOvIf2Ur5sxpS0QXryzoYLNXCXD1DFJ1EUBcvoLkwrMxLQ9ijx7aXW1cq5x2z7Syf9MRp1RgMzO9n2eNzD5V200t826qw4t"
  whSec: "whsec_oDJqklbPr9Dg90UBsnTbhHxvGRLbLye4"

kafka:
  bootstrapAddress: kafka:9092 # localhost:9093
  groupId: 1

elasticsearch:
  url: elasticsearch:9200

kibana:
  url: kibana:5601

resources:
  path: /
