spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: mail.privateemail.com
    port: 587
    username: support@logsight.ai
    password: tel12-5DOS
  thymeleaf:
    check-template: true
    check-template-location: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

server:
  error:
    include-stacktrace: ON_PARAM
  forward-headers-strategy: framework

logsight:
  user: offline
  common:
    base-url: "http://localhost:4200"
    logsight-email: "support@logsight.ai"

  application-rpc:
    zeromq:
      protocol: "tcp"
      host: "0.0.0.0"
      port: 5555
      timeout: 10000    # Seconds

  logs:
    stream:
      zeromq:
        protocol: "tcp"
        host: "*"
        port: 5559
    control-rpc-in:
      zeromq:
        protocol: "tcp"
        host: "*"
        port: 5558
        topic: "result_init"
    control-rpc-out:
      zeromq:
        protocol: "tcp"
        host: "*"
        port: 5557

  elasticsearch:
    scheme: "http"
    host: "localhost"
    port: "9200"
    credentials:
      username: "elastic"
      password: "elasticsearchpassword"

  kibana:
    scheme: "http"
    host: "localhost"
    port: "5601"
    header: "kbn-xsrf"

  result-api:
    rest:
      scheme: "http"
      host: "localhost"
      port: 5554
      compare-path: "api/v1/compare"

  token:
    minutes: 15
