spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight

  servlet:
    multipart:
      enabled: true
      max-file-size: 550MB
      max-request-size: 550MB

email:
  host: smtp.gmail.com
  port: 587
  username: noreply.logsight@gmail.com
  password: logsight2021123!

app:
  baseUrl: https://logsight.ai/
  baseUrlTry: https://logsight.ai/
  qualityUrl: http://data-input-rest-api:5444/

#change this for prod
stripe:
  sk: "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"
  whSec: "whsec_brxduRlHbT0O9Z6EooHI0Ps2J4EQqDxQ"

kafka:
  bootstrapAddress: kafka:9092 # localhost:9093
  groupId: 1

elasticsearch:
  url: elasticsearch:9200

kibana:
  url: kibana:5601

resources:
  path: /
