spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: "default"

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

email:
  host: mail.privateemail.com
  port: 587
  username: support@logsight.ai
  password: tel12-5DOS

user:
  userAccountBootstrap: true
  appLimit: 5000

app:
  baseUrl: http://localhost:4200
  qualityUrl: http://localhost:5444/
  baseUrlTry: http://localhost:4200/

kibana.url: kibana:5601

continuous-verification:
  host: logsight-continuous-verification
  port: 5554

elasticsearch:
  url: elasticsearch:9200
  username: elastic
  password: elasticsearchpassword

resources:
  path: /

---
spring.config.activate.on-profile: ide

spring.datasource.url: jdbc:postgresql://localhost:5432/logsight
spring.kafka.bootstrap-servers: localhost:9093

elasticsearch.url: localhost:9200

kibana.url: localhost:5601

continuous-verification.host: localhost

app:
  baseUrl: http://localhost:4200
  qualityUrl: http://data-input-rest-api:5444/

resources.path: src/main/resources/

---
spring.config.activate.on-profile: web-preprod

app:
  baseUrl: https://demo.logsight.ai/
  baseUrlTry: https://demo.logsight.ai/
  qualityUrl: https://demo.logsight.ai:5444/

---
spring.config.activate.on-profile: web-prod

app:
  baseUrl: https://logsight.ai/
  baseUrlTry: https://logsight.ai/
  qualityUrl: https://logsight.ai:5444/

user:
  userAccountBootstrap: false
  appLimit: 5
