spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

email:
  host: smtp.gmail.com
  port: 587
  username: logsight.ai.noreply@gmail.com
  password: makedonija123

app:
  baseUrl: http://localhost:4200

kafka:
  bootstrapAddress: localhost:9093 # localhost:9093
  groupId: 1

elasticsearch:
  url: localhost:9200

kibana:
  url: localhost:5601

resources:
  path: src/main/resources/