spring:
  main:
    banner-mode: "off"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/logsight}
    username: ${SPRING_DATASOURCE_USERNAME:logsight}
    password: ${SPRING_DATASOURCE_PASSWORD:logsight}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: mail.privateemail.com
    port: 587
    username: support@logsight.ai
    password: tel12-5DOS  # TODO: this is dangerous when we publish the containers
  thymeleaf:
    check-template: true
    check-template-location: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    baselineOnMigrate: true
    enabled: true

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

server:
  error:
    include-stacktrace: ON_PARAM
  forward-headers-strategy: framework

logsight:
  common:
    deployment: ${LOGSIGHT_DEPLOYMENT:stand-alone}  # "web-service"
    base-url: ${LOGSIGHT_URL:http://localhost:4200}
    logsight-email: ${LOGSIGHT_EMAIL:support@logsight.ai}

  application-rpc:
    zeromq:
      protocol: "tcp"
      host: ${APP_RPC_ZMQ_HOST:0.0.0.0}
      port: ${APP_RPC_ZMQ_PORT:5555}
      timeout: ${APP_RPC_ZMQ_TIMEOUT:10000}    # Milliseconds

  logs:
    stream:
      queue:
        max-size: 1000000
      zeromq:
        protocol: "tcp"
        host: "*"
        port: ${LOGS_STREAM_ZMQ_PORT:5559}
        hwm: 10000000
    control-rpc-in:
      zeromq:
        protocol: "tcp"
        host: "*"
        port: ${LOGS_CTRL_RPC_IN_ZMQ_PORT:5558}
        topic: "result_init"
    control-rpc-out:
      zeromq:
        protocol: "tcp"
        host: "*"
        port: ${LOGS_CTRL_RPC_OUT_ZMQ_PORT:5557}

  elasticsearch:
    scheme: ${ELASTICSEARCH_SCHEME:http}
    host: ${ELASTICSEARCH_HOST:localhost}
    port: ${ELASTICSEARCH_PORT:9200}
    credentials:
      username: ${ELASTICSEARCH_USERNAME:elastic}
      password: ${ELASTICSEARCH_PASSWORD:elasticsearchpassword}

  kibana:
    scheme: ${KIBANA_SCHEME:http}
    host: ${KIBANA_HOST:localhost}
    port: ${KIBANA_PORT:5601}
    header: "kbn-xsrf"

  result-api:
    rest:
      scheme: ${RESULT_API_SCHEME:http}
      host: ${RESULT_API_HOST:localhost}
      port: ${RESULT_API_PORT:5554}
      compare-path: ${RESULT_API_COMPARE_PATH:api/v1/compare}

  token:
    minutes: 15
