spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight

  servlet:
    multipart:
      enabled: true
      max-file-size: 550MB
      max-request-size: 550MB

email:
  host: smtp.gmail.com
  port: 587
  username: noreply.logsight@gmail.com
  password: logsight2021123!

app:
  baseUrl: https://demo.logsight.ai/

kafka:
  bootstrapAddress: kafka:9092 # localhost:9093
  groupId: 1

elasticsearch:
  url: elasticsearch-demo:9200

kibana:
  url: kibana-demo:5601/demo

resources:
  path: /
