spring:
  security:

  elasticsearch:
    username: "elastic"
    password: "elasticsearchpassword"
    uris: "localhost:9200"
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/logsight   # jdbc:postgresql://localhost:5432/logsight
    username: logsight
    password: logsight
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: logsight.ai.noreply@gmail.com
    password: makedonija123
    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: true
    properties.mail.transport.protocol: smtp
  thymeleaf:
    check-template: true
    check-template-location: true


logsight:
  elasticsearch:
    host: "localhost"
    port: "9200"
    protocol: "http"
    credentials:
      username: "elastic"
      password: "elasticsearchpassword"

  kibana:
    host: "localhost"
    port: "5601"

  token:
    duration: 15



common-config:
  base-url: http://localhost:4200
  logsight-email: info@logsight.ai
