spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5431/logsight_test
    username: logsight
    password: logsight