package ai.logsight.backend.token.config

import org.springframework.boot.context.properties.EnableConfigurationProperties

@EnableConfigurationProperties(PasswordResetTokenConfigurationProperties::class)
class PasswordResetTokenConfiguration
