
CREATE TABLE logs_receipt
(
    id             UUID                                     NOT NULL,
    order_num      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logs_count     INTEGER                                  NOT NULL,
    CONSTRAINT pk_logs_receipt PRIMARY KEY (id)
);

CREATE TABLE time_selection
(
    id             UUID NOT NULL,
    name           VARCHAR(255),
    start_time     VARCHAR(255),
    end_time       VARCHAR(255),
    date_time_type VARCHAR(255),
    user_id        UUID,
    CONSTRAINT pk_time_selection PRIMARY KEY (id)
);

CREATE TABLE token_entity
(
    token          UUID NOT NULL,
    user_id        UUID,
    token_type     INTEGER,
    token_duration BIGINT,
    expires_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tokenentity PRIMARY KEY (token)
);

CREATE TABLE users
(
    id                UUID                        NOT NULL,
    key               VARCHAR(255)                NOT NULL UNIQUE,
    email             VARCHAR(255)                NOT NULL,
    password          VARCHAR(255)                NOT NULL,
    date_created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    activation_date   TIMESTAMP WITHOUT TIME ZONE,
    has_paid          BOOLEAN                     NOT NULL,
    used_data         BIGINT,
    approaching_limit BOOLEAN,
    available_data    BIGINT,
    activated         BOOLEAN                     NOT NULL,
    user_type         INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);


ALTER TABLE logs_receipt
    ADD CONSTRAINT uc_logs_receipt_order_num UNIQUE (order_num);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE time_selection
    ADD CONSTRAINT FK_TIME_SELECTION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);